### ISSUE TITLE
Play project build NullPointerException

### ISSUE THREAD

**Issue by reid-me** [ikeike443/HudsonPluginForPlay#22]
I try the hundson 2.1.0 free-style software project and uses HudsonPluginForPlay  0.0.9-SNAPSHOT

As a result of that,

java.lang.NullPointerException
        at com.gmail.ikeike443.PlayAutoTestBuilder.perform(PlayAutoTestBuilder.java:141)
        at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:19)
        at hudson.model.AbstractBuild$AbstractRunner.perform(AbstractBuild.java:631)
        at hudson.model.Build$RunnerImpl.build(Build.java:172)
        at hudson.model.Build$RunnerImpl.doRun(Build.java:137)
        at hudson.model.AbstractBuild$AbstractRunner.run(AbstractBuild.java:429)
        at hudson.model.Run.run(Run.java:1367)
        at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:46)
        at hudson.model.ResourceController.execute(ResourceController.java:88)
        at hudson.model.Executor.run(Executor.java:145)

I temporary fix 
project - configure - [Check] This build is parameterized - add dummy string parameter

Plese check issue. Your plugin is very useful.
Thanks.

**Comment by ikeike443** [comment]
Thank you for your information.

Did you check out it from HEAD?
HEAD is still under testing, not released.
Released version is Jenkins-ci/play-plugin and you can get it from jenkins update center.

Btw, It is very useful information and I'll check it and fix it.
Thank you very much!

Keep in touch! ;-)

**Comment by reid-me** [comment]
thank you for your response. i first time used the 0.0.1 default build. but result of the same.

**Comment by ikeike443** [comment]
Thank you.

It is fixed.
