### ISSUE TITLE
At first build without configuring app_path, build must fail.

### ISSUE THREAD

**Issue by ikeike443** [ikeike443/HudsonPluginForPlay#28]
``` Java
FATAL: null
java.lang.NullPointerException
    at com.gmail.ikeike443.PlayAutoTestBuilder.perform(PlayAutoTestBuilder.java:131)
    at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:19)
    at hudson.model.AbstractBuild$AbstractRunner.perform(AbstractBuild.java:682)
    at hudson.model.Build$RunnerImpl.build(Build.java:177)
    at hudson.model.Build$RunnerImpl.doRun(Build.java:139)
    at hudson.model.AbstractBuild$AbstractRunner.run(AbstractBuild.java:448)
    at hudson.model.Run.run(Run.java:1376)
    at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:46)
    at hudson.model.ResourceController.execute(ResourceController.java:88)
    at hudson.model.Executor.run(Executor.java:175)
```

**Comment by ikeike443** [comment]
done.
https://github.com/ikeike443/HudsonPluginForPlay/commit/3a45e349888a6028abb1366b49fb825726af58af
