### ISSUE TITLE
Build step 'Play!' marked build as failure

### ISSUE THREAD

**Issue by jostyee** [ikeike443/HudsonPluginForPlay#41]
I've configured settings as the plugin's page instructed and set play path to /home/ec2-user/play-1.2.5.3/play which exists but jenkins build always failed at:

```
play path is /home/ec2-user/play-1.2.5.3/play
Executing /home/ec2-user/play-1.2.5.3/play clean "/var/lib/jenkins/jobs/proj-web/workspace" 
[workspace] $ /home/ec2-user/play-1.2.5.3/play clean /var/lib/jenkins/jobs/proj-web/workspace
Build step 'Play!' marked build as failure
Finished: FAILURE
```

the jenkins log showed:

```
java.io.IOException: Cannot run program "/home/ec2-user/play-1.2.5.3/play" (in directory "/var/lib/jenkins/jobs/proj-web/workspace"): error=13, Permission denied
    at java.lang.ProcessBuilder.start(ProcessBuilder.java:1047)
    at hudson.Proc$LocalProc.<init>(Proc.java:244)
    at hudson.Proc$LocalProc.<init>(Proc.java:216)
    at hudson.Launcher$LocalLauncher.launch(Launcher.java:803)
    at hudson.Launcher.launch(Launcher.java:558)
    at hudson.Launcher.launch(Launcher.java:490)
    at hudson.Launcher.launch(Launcher.java:482)
    at com.gmail.ikeike443.PlayAutoTestBuilder.perform(PlayAutoTestBuilder.java:159)
```

Tried chmod 777 to both the play dir and the workspace dir without luck, was I missing something?

**Comment by jostyee** [comment]
Problem resolved. I placed play dir into another user's home, which jenkins has no permission to visit.
